[build-system]
requires = ['Django', 'setuptools>=40.8.0', 'wheel']
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py36']
skip-string-normalization = true

[tool.isort]
profile = 'black'
